# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 331)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setGeometry(QtCore.QRect(70, 70, 261, 191))
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-top-color: rgb(170, 255, 0);")
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setElideMode(QtCore.Qt.ElideNone)
        self.tabs.setDocumentMode(False)
        self.tabs.setObjectName("tabs")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 40, 91, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 90, 91, 23))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabs.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 91, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.tabs.addTab(self.tab, "")

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "Login"))
        self.pushButton_3.setText(_translate("Dialog", "SIgn Up"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("Dialog", "Users"))
        self.pushButton.setText(_translate("Dialog", "Login"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("Dialog", "Moderator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
